name: Create Testing Build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'forge-1.20.1'
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Get Version
      uses: BrycensRanch/read-properties-action@v1
      id: version
      with:
        file: gradle.properties
        property: greate_version
    - name: Build
      uses: gradle/gradle-build-action@v2.4.2
      with:
          cache-disabled: true
          arguments: build
    - name: Upload Testing Build
      uses: actions/upload-artifact@v4
      with: 
        name: greate-${{ steps.version.outputs.greate_version }}-testing
        path: build/libs/*[0-9].jar
